### ISSUE TITLE
/user/game/category/pb times out

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#140]
Using the default example of https://splits.io/api/v3/users/glacials/games/sms/categories/852/pb causes a timeout more often than it successfully returns a response.

**Comment by glacials** [comment]
investigated the "find pb" queries a bit, they don't seem to be the problem. i think it's parsing, as the same problem occurs when accessing that run directly via https://splits.io/api/v3/runs/1686 as well. suspicions for now are around taking too long to parse split history, or taking too long to copy the file to memory.

when i have time later i will look into if we can opt to not parse history for the endpoints that don't need it, and see if we can gain some of this time back until we are ready to really overhaul parsing.

**Comment by BatedUrGonnaDie** [comment]
The only reason I brought this timeout up specifically is because /users/:user/pbs doesn't timeout at all and I thought it was weird that the endpoint with less runs was taking longer.

**Comment by glacials** [comment]
Yeah this is because endpoints that return multiple runs don't include splits, just general run information like time and game and category and all that. All that info is stored in the database, so we don't need to parse the original file when answering.

I think I'm going to end up putting splits in the database eventually too, just so we don't ever need to parse more than once, which I think would solve a lot of these timeouts.

**Comment by BatedUrGonnaDie** [comment]
Ah, that would explain that.

**Comment by BatedUrGonnaDie** [comment]
Looks like the history change fixed this.
