### ISSUE TITLE
API returns 500 error for valid runs

### ISSUE THREAD

**Issue by Lighnat0r** [glacials/splits-io#167]
Things such as https://splits.io/api/v3/runs/c6 return an error even though the run clearly exists: https://splits.io/c6
This happens for a significant number of runs, although most runs are working fine.

**Comment by glacials** [comment]
Thanks for pointing this out! Seems this happens when a run has a category with a `nil` game, which happens for runs that come from timers that don't have distinct game/category fields (like WSplit). In those runs we set the category name to the "title" field in WSplit, and the category game to `nil`.

We recently bumped up to Rails 5, so maybe something with the resulting ActiveModelSerializers upgrade changed how that type of relationship is serialized, causing 500s.

But, having categories with `nil` games feels dirty to begin with, as that's not really how it works in real life. So 5204177f43133b24eb7718d37584187f20ad4f03 changes this behavior to set the category itself to `nil`. We'll lean on `Run#name` instead for these runs.

I've tested this with a few of the victim runs and it seems to work. However the fix applies to data, not code, so it will take some time to propagate to all existing runs. 69f0f3dc519d42c32629f6bc5f0f8be56e23a739 will accelerate this. I'll leave this issue open for a bit while it does its work.

Thanks again!
