### ISSUE TITLE
Expose run history in api for livesplit runs

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#199]
If it wouldn't incur too much of a speed penalty it would be cool to have.

**Comment by glacials** [comment]
Ran some quick benchmarks across a few runs ranging from no history to ~50 attempts of history (exact number varies as not all splits have all history entries). Saw at minimum no increase and at maximum about a 12x increase. Average seemed to be around 5x or 6x as slow when parsing history vs. skipping over it.

Because of this I'm definitely keeping skipping as the new default everywhere, but I've added a flag in v4 API to include history: https://splits.io/api/v4/runs/3nm/splits?historic=1

I'm going to try to set up better monitoring so I can see how often these hits timeout, and use that to inform decisions about better caching, putting more work into optimizing parsing, etc.

If this solves the issue can you close :smile_cat:

**Comment by BatedUrGonnaDie** [comment]
Actually I was wondering about the run history, which keeps track of all the finished run times that you have.  In 1.4.2 files its called RunHistory and it's right at the top.

**Comment by glacials** [comment]
Ah I see, I misread. Same thing for run history then: https://splits.io/api/v4/runs/3nm?historic=1

Normal run hits don't need to parse anything, as all the information is in the database, so similar argument to about around having no history be the default.

**Comment by BatedUrGonnaDie** [comment]
Sweet, thank you very much :smile:
