### ISSUE TITLE
Compare page should become a first-class citizen

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#263]
This task originally had a smaller scope, but as I was writing it I realized what I'd actually like is a comparison page that is more of a first-class citizen in general.

Right now the comparison page is adaptable enough to compare any two splits, even those of different games! What would be great is a UI flow for comparing any two splits of a given game, or at least any two of your own splits. This would be similar to the "compare to best on record" or the rivals system.

Proposed flow:
1. Go to a splits page (probably PB)
2. Click "compare" link (would replace "compare to best on record" or "compare to my PB")
3. Be presented a list of splits associated with the same game [alias] and category [alias]. Best on record, your PB, and your last PB are all be stuck to the top in their own UI elements (or at least highlighted in some way). There is also a box available for entering any splits ID.
4. Select a set of splits against which to compare.
5. Be presented the current compare page, plus a multitude of stats and graphs below the splits timeline.

Background:
I recently had someone ask me if they could compare one PB of theirs to another on Splits I/O. I figured it was possible, but I had to go through the cumbersome process of opening both PBs to grab the IDs, and then adding "/<id1>/compare/<id2>" to the URL bar. I had also been bragging about the awesome stats and graphs provided on PBs and was a bit disappointed to find none on the comparison page. It would be awesome if there were some! :)

**Comment by glacials** [comment]
100% agree. For a feature I use so much it should feel way much more natural to use than it does today. And actually I'm upset that they're even as hard to find as they are. imo the first thing you see after uploading a run should be a comparison with your rival's run or your friends' runs or anything. Seeing a run on its own is ok but the default should be a comparison.

I really think we should basically merge the current run page with the comparison page, such that when you visit someone else's PB you're already immediately seeing it compared to yours, or their previous run, or WR or whatever, and you can swap it out for other runs without even a page load. That is the ultimate sick futureworld I want to get to.

Charts is something I hadn't even thought about for comparisons but now that you've brought it up I can't stop thinking up cool ones to display. Like 1D tug-of-war charts for each segment best, or "race to XX:YY" charts that develop over months, even containing any number of runners. Even just taking the charts on the current stats page and putting both runners in one chart, as dual-bar charts and stuff.

The stats page is also the slowest page right now because it has parse and sift through the entire run history, and with the recent new DynamoDB changes I've been making I want to improve from that end as well -- especially if this page is going to be the new primary page on the site.

**Comment by jhobz** [comment]
I love the idea of comparison showing up on the default page. Could probably default to your previous PB (if one exists) with a dropdown or other form of selection to pick rival or WR.
