### ISSUE TITLE
Splits aren't claimed properly when submitting to Speedrun.com through LiveSplit

### ISSUE THREAD

**Issue by wooferzfg** [glacials/splits-io#290]
After LiveSplit uploads splits to splits-io and then submits to speedrun.com, it sends a PUT request to splits-io with the claim token and speedrun.com run id. As far as I know, this used to claim the splits with the Twitch account associated with the speedrun.com profile of the user whose run it was, but instead, the splits aren't assigned to anyone. The speedrun.com run id in the splits-io splits is updated properly, however.

**Comment by glacials** [comment]
This is intentional. The claim token acts only as proof that the program making the request uploaded the splits. It does not serve as proof that the program making the request is acting on behalf of any specific user.

If the run's `user_id` could be set by any program passing in a claim token, a malicious person could upload splits to my Splits I/O account without my permission, which I don't want.

Currently the only way to claim a run after having uploaded it is to have the logged-in user visit the URL in `uris.claim_uri` in the [run upload API response][1]. Their Splits I/O session cookie serves as the missing proof.

This has its own small problems, like the fact that you could just tell someone to click on a link and then they'd own a run against their will, but it covers the really bad cases. The ideal situation is definitely OAuth or something like it (see #227).

[1]: https://github.com/glacials/splits-io/blob/master/docs/api.md#post-runs

**Comment by glacials** [comment]
Closing because OAuth is now implemented (see [docs/api.md][1]).

[1]: https://github.com/glacials/splits-io/blob/master/docs/api.md#uploading-runs-on-behalf-of-a-user-1
