### ISSUE TITLE
Several features of the stats page do not check timing method

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#371]
The best description of this is probably to check here: https://splits.io/2696/stats?timing=game

Several graphs are wrong (or do not load), segment information still uses Real time, Run information can go negative, etc.

**Comment by BatedUrGonnaDie** [comment]
I believe the runs haven't been reparsed yet for the new SoB for gametime and such.  If you look at the return from the API for that run it shows all the history for every split as '0' seconds for gametime, which is why the graphs are breaking.  I made sure to select the right field based off the url param this time around when redo'ing the graphing.

**Comment by jhobz** [comment]
How do I force it to reparse again? "?parse=true"?

**Comment by BatedUrGonnaDie** [comment]
I believe its `?reparse=1`

**Comment by BatedUrGonnaDie** [comment]
#373 addresses gametime history entries for segments always showing as 0, apparently we just weren't extracting that info out of the file.

**Comment by BatedUrGonnaDie** [comment]
I believe these should all be fixed.  Do you see anything that looks off @jhobz ?

**Comment by jhobz** [comment]
From what I can tell, everything seems fixed! Now that the data is correct, I'm also getting to play around with these new graphs for the first time and they're _awesome!_ Nice upgrade; the zooming is especially fantastic for when you need to avoid an outlier.
