### ISSUE TITLE
Duplicate results in search

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#423]
![firefox_2018-07-06_16-45-20](https://user-images.githubusercontent.com/7030913/42404185-fd9d5342-813b-11e8-928f-87e73593a5b4.png)

**Comment by glacials** [comment]
Thanks, should be fixed on or around 5b029d33fe176adc8ef068cab8c6a02bd25bd392 although messily. We are searching GameAliases and not Games, so we potentially get one result per GameAlias that matches the query. We're unable to use `DISTINCT` to filter these down because SQL distinctness is based on the values in the `SELECT`, and in this query the search score is one of the items selected, which can be different for each alias.

There must be a better way to do this, but I don't know what it is. For now this adds one more query to searches which isn't a deal breaker. Also had to had a gem in cb0cd0de380f89dfff68a177a5997530cf6ba1f4 to maintain search rank order, which is normally lost when piping IDs from one query into another.
