### ISSUE TITLE
Sum of Bests appears to be parsed/calculated incorrectly sometimes

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#427]
From [2tka](https://splits.io/2tka?timing=game):
Sum of Best on Splits I/O does not match SoB on splits (represented here by Best Possible Time).

![image](https://user-images.githubusercontent.com/1765799/42642327-9fff0360-85c4-11e8-8ac3-00a951529584.png)

While the screenshot above depicts gametime, the realtime SoB is also off. I tried cleaning sum of best through LiveSplit upon first noticing the discrepancy (before taking the screenshot), but the result is still off.

**Comment by glacials** [comment]
Thanks for the report! LiveSplit's default "sum of best" is actually a shortest-path algorithm through all runs you've ever done. Splits I/O's sum of best, where we... well, [sum your bests][1], is what LiveSplit calls "simple sum of best". cc @CryZe / @wooferzfg

We can fix the inconsistency by using livesplit-core's sum of best component instead of calculating it ourselves (see #377), and perhaps expose simple sum of best somewhere else if we still want it. For now, can you try turning on "simple sum of best" in LiveSplit's settings and see if that makes the two numbers come into sync?

[1]: https://github.com/glacials/splits-io/blob/master/app/models/concerns/unparsed_run.rb#L201-L203

**Comment by BatedUrGonnaDie** [comment]
Currently the analytics module that contains total playtime and SoB calculations isn't exposed in a released version, only on the master branch.  I've been waiting for a new release to implement those instead of hand rolling the calculations like we have been before.

**Comment by CryZe** [comment]
I can release a new version over the weekend.

**Comment by BatedUrGonnaDie** [comment]
Take your time cryze, just whenever you get a chance.
