### ISSUE TITLE
[Feature] Splits uploaded that use subsplits should format as such on the splits page (possibly with extra stats)

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#428]
Any runs uploaded in the subsplits format could display with custom styling. Custom stats about the top-level segments could be displayed in a custom box alongside the normal split stats.

**Comment by moorecp** [comment]
@glacials I have a version of this working, but it's inefficient due to subsplit information not really being stored anywhere. Issue #122 looked like it was going to deal with this, but it got back burnered due to upcoming changes in LiveSplit. Did those changes ever happen? If not, is there a desire to go ahead and move forward anyway?

**Comment by BatedUrGonnaDie** [comment]
I'm currently rewriting the parsing of splits files, so if there is any special handling you want for subsplits now is a good time to add it since I'm going to be adding some other things hopefully.

**Comment by CryZe** [comment]
Oh yeah, the split configurations mentioned in that issue aren‘t going to happen in that way. However there will be dedicated subsplits and custom variables support, which is basically the same idea, but with subsplits being elevated to something more dedicated. Both of these already exist as open pull requests in livesplit-core and they both work, but aren‘t fully mergable yet. Since I‘m currently focusing on implementing the speedrun.com and splits.io integration, they are probably going to be finished afterwards. So yeah, you can try to parse the old style subsplits yourself for now if you want as they are fairly easy to recognize via the split names, but it‘ll definitely change in the future (but I guess whatever UI and database changes this entails would still apply then, so this can certainly be implemented).

**Comment by moorecp** [comment]
It's definitely worth a discussion. It seems like having a potential parent object above segments that represent the subsplit would be good. Also, is subsplit even the right terminology in this case? Segments in Splits.io map to splits in LiveSplit, but really what you have are splits and macro splits. Something like a MacroSegment in that it exists above the Segment. It could have the name from the `{....}` part of the split and times could be rolled up into it.

I'm just sort of spitballing here and am thinking about what I implemented in my test branch for this feature.

**Comment by CryZe** [comment]
Yeah we call it split groups in the livesplit-core branch / LiveSplit One.

**Comment by glacials** [comment]
Not to get too abstract here, but is a run:segment relationship the same as a segment:subsegment relationship? Could this data model be simplified into one "segment"-like object that can itself contain other segments?

**Comment by moorecp** [comment]
It could be done like that, but I'm not sure if it's best. In the LSS file, there is no relationship between segments and subsegments. The overarching segment group is simply indicated by a segment with a name starting with `{Whatever name} Segment name`. Even that segment is a subsegment. The value contained withing the `{}` is just used as the title for the segment group.

I feel like since the actual representation of segments and segment groups is that the segment that indicates group information is itself also a segment means that we probably want something representing the group apart from just a segment.

![subsplits](https://user-images.githubusercontent.com/293433/65542242-cb825b00-dedc-11e9-8402-e97f294656c8.png)

This is an example of a run with subsplits. The left is on the current live site and shows exactly what's in the LSS vs a rough example of what I have locally showing the parent/child relationship even though none really exists. Segment 3 is the one that causes the segment/segment group relationship.

**Comment by glacials** [comment]
Cool I generally like this UI, what do you mean when you say it's inefficient? I understand the metadata about groups is stored in the split/segment names themselves, do you just mean it's inefficient to do string parsing on all segment names to determine the right groupings?

Since it sounds like the way subsplits are getting an overhaul in the medium-term future, I don't think we should parse them at parse-time and change our data model to support them yet. Let's wait until the support is solidified in livesplit-core before making a big change on our end. But I'm perfectly fine doing string parsing for now if the slowdown isn't noticeable.

Also I assume stats and charts won't be viewable on the groups (e.g. "Ceres Station") themselves, is that correct? & Any ideas on how / whether to display them in the timeline?

**Comment by moorecp** [comment]
The inefficient comment is in regards to calculating all the segment group related stats and such. In my current branch, it's all happening in ruby and just isn't nearly as fast as the DB, although I'm guessing I could do things better than I am currently. I just wanted to get something working and see how it behaved.

The individual stats and charts work well. I didn't try to add them to the aggregate charts, though. Here's an example of a segment group chart and stats:

<img width="697" alt="Screen Shot 2019-09-24 at 8 38 14 PM" src="https://user-images.githubusercontent.com/293433/65560106-4febd280-df0b-11e9-994b-9fbbb735692f.png">

**Comment by glacials** [comment]
Oh ok nice! Well whenever you feel it's ready and/or needs some feedback, feel free to open a PR and I'd be happy to take a look!
